import { useEffect, useState } from "react";
import { FileUp, FlaskConical, Search } from "lucide-react";
import DataTable from "../components/DataTable.jsx";
import { PanelTitle, ProfileCard } from "../components/PanelShared.jsx";
import { API } from "../utils/api.js";

const exampleResults = [
  { parameter: "Hemoglobin", value: "13.5", unit: "g/dL", status: "Normal" },
  { parameter: "WBC Count", value: "7500", unit: "/mm3", status: "Normal" },
  { parameter: "Platelets", value: "2.5", unit: "lakh/mm3", status: "Normal" }
];

export default function LabTechnicianPanel({ user, authHeaders, requireLogin }) {
  const [requests, setRequests] = useState([]);
  const [q, setQ] = useState("");
  const [selected, setSelected] = useState(null);
  const [resultsText, setResultsText] = useState("Hemoglobin,13.5,g/dL,Normal\nWBC Count,7500,/mm3,Normal\nPlatelets,2.5,lakh/mm3,Normal");
  const [reportFile, setReportFile] = useState(null);
  const [statusFilter, setStatusFilter] = useState("pending");
  const [message, setMessage] = useState("");

  const loadRequests = () => {
    fetch(`${API}/lab/requests`, { headers: authHeaders })
      .then((response) => {
        if (response.status === 401 || response.status === 403) {
          requireLogin("lab_technician", "lab_technician");
          return [];
        }
        return response.json();
      })
      .then((data) => Array.isArray(data) && setRequests(data))
      .catch(() => setMessage("Backend is not connected. Start backend server first."));
  };

  useEffect(() => {
    loadRequests();
    const timer = setInterval(loadRequests, 5000);
    return () => clearInterval(timer);
  }, []);

  const markCollected = async (row) => {
    const response = await fetch(`${API}/lab/requests/${row._id}/collect`, { method: "PATCH", headers: authHeaders });
    const data = await response.json();
    if (!response.ok) return setMessage(data.message || "Unable to mark sample collected.");
    setRequests((current) => current.map((item) => (item._id === data._id ? data : item)));
    setMessage(`Sample collected for ${data.patientName}.`);
  };

  const parseResults = () => resultsText.split("\n").map((line) => {
    const [parameter, value, unit, status] = line.split(",").map((item) => item.trim());
    return { parameter, value, unit, status };
  }).filter((item) => item.parameter);

  const readPdfFile = () => new Promise((resolve, reject) => {
    if (!reportFile) return resolve({});
    if (reportFile.type !== "application/pdf") return reject(new Error("Please select a PDF file."));
    if (reportFile.size > 5 * 1024 * 1024) return reject(new Error("PDF must be 5 MB or smaller."));

    const reader = new FileReader();
    reader.onload = () => {
      const result = String(reader.result || "");
      resolve({
        reportFileName: reportFile.name,
        reportMimeType: reportFile.type,
        reportData: result.includes(",") ? result.split(",")[1] : result
      });
    };
    reader.onerror = () => reject(new Error("Unable to read selected PDF."));
    reader.readAsDataURL(reportFile);
  });

  const uploadReport = async () => {
    if (!selected) return setMessage("Open a lab request first.");
    let uploadedFile = {};
    try {
      uploadedFile = await readPdfFile();
    } catch (error) {
      return setMessage(error.message);
    }
    const response = await fetch(`${API}/lab/requests/${selected._id}/results`, {
      method: "PATCH",
      headers: { "Content-Type": "application/json", ...authHeaders },
      body: JSON.stringify({
        results: parseResults(),
        reportFileName: uploadedFile.reportFileName || selected.reportFileName || `${selected.testName}-report.pdf`,
        reportMimeType: uploadedFile.reportMimeType || selected.reportMimeType,
        reportData: uploadedFile.reportData || selected.reportData,
        remarks: "Report generated by lab technician."
      })
    });
    const data = await response.json();
    if (!response.ok) return setMessage(data.message || "Unable to upload report.");
    setRequests((current) => current.map((item) => (item._id === data._id ? data : item)));
    setSelected(data);
    setReportFile(null);
    setMessage(`Report uploaded for ${data.patientName}.`);
  };

  const reportLink = (row) => `${API}/lab/requests/${row._id}/report-file`;

  const openReport = async (row) => {
    setMessage("");
    try {
      const response = await fetch(reportLink(row), { headers: authHeaders });
      if (response.status === 401 || response.status === 403) return requireLogin("lab_technician", "lab_technician");
      if (!response.ok) return setMessage("Unable to open PDF report.");

      const blob = await response.blob();
      const url = URL.createObjectURL(blob);
      window.open(url, "_blank", "noopener,noreferrer");
      setTimeout(() => URL.revokeObjectURL(url), 30000);
    } catch {
      setMessage("Unable to open PDF report.");
    }
  };

  const filtered = requests.filter((row) => {
    const matchesSearch = !q || row.patientName?.toLowerCase().includes(q.toLowerCase()) || row.opdId?.toLowerCase().includes(q.toLowerCase()) || row.testName?.toLowerCase().includes(q.toLowerCase());
    const matchesStatus = statusFilter === "all" || (statusFilter === "pending" ? !["reported", "reviewed"].includes(row.status) : ["reported", "reviewed"].includes(row.status));
    return matchesSearch && matchesStatus;
  });
  const emptyLabMessage = q
    ? "No lab request found for this OPD ID. Doctor must prescribe a lab test first, then the patient can book it."
    : "No lab requests yet. Requests appear here after a doctor prescribes a lab test.";

  return (
    <section className="dashboard lab-theme">
      <PanelTitle title="Lab Technician Desk" text="Collect samples, process tests, enter results and upload reports." />
      <ProfileCard user={user} />
      <div className="two-col">
        <div className="panel">
          <h2>Sample Collection</h2>
          <div className="inline">
            <Search size={16} />
            <input placeholder="Search OPD, patient or test" value={q} onChange={(event) => setQ(event.target.value)} />
            <select value={statusFilter} onChange={(event) => setStatusFilter(event.target.value)}>
              <option value="pending">Pending Reports</option>
              <option value="completed">Completed Reports</option>
              <option value="all">All Reports</option>
            </select>
          </div>
          {!filtered.length && <p className="notice">{emptyLabMessage}</p>}
          <DataTable
            title="Test Requests"
            rows={filtered}
            columns={["opdId", "patientName", "testName", "category", "bookingDate", "status"]}
            action={(row) => (
              <>
                {row.status === "requested" || row.status === "booked" ? <button onClick={() => markCollected(row)}>Collect</button> : <span>{row.status}</span>}
                <button onClick={() => { setSelected(row); setReportFile(null); setResultsText(row.results?.length ? row.results.map((item) => `${item.parameter},${item.value},${item.unit},${item.status}`).join("\n") : resultsText); }}>Open</button>
                {["reported", "reviewed"].includes(row.status) && <button type="button" onClick={() => openReport(row)}>View PDF</button>}
              </>
            )}
          />
        </div>
        <div className="panel">
          <h2>Report Upload</h2>
          {selected ? <p className="patient-summary">{selected.patientName} - {selected.testName} - {selected.status}</p> : <p className="notice">Open a request to enter results.</p>}
          <label>Result Parameters<textarea value={resultsText} onChange={(event) => setResultsText(event.target.value)} /></label>
          <label>Upload PDF Report<input type="file" accept="application/pdf" onChange={(event) => setReportFile(event.target.files?.[0] || null)} /></label>
          {selected?.reportFileName && <p className="notice">Current report: {selected.reportFileName}</p>}
          <div className="sample-report">
            <FlaskConical />
            <strong>Example: CBC</strong>
            {exampleResults.map((item) => <span key={item.parameter}>{item.parameter}: {item.value} {item.unit} - {item.status}</span>)}
          </div>
          {message && <p className="notice">{message}</p>}
          <button className="primary" onClick={uploadReport}><FileUp size={16} />Upload Report</button>
        </div>
      </div>
    </section>
  );
}
